export enum WorkHeader {
    PROGRAMMER = "PROGRAMMER",
    ADMINSTRATOR = "ADMINSTRATOR",
    DOCTOR = "DOCTOR",
    SOTUVCHI = "SOTUVCHI",
    MARKETING = "MARKETING",
    FANUSTOZI = "FANUSTOZI",
    AVTOMABIL_BIZNESI = "AVTOMABIL_BIZNESI",
}